---
- name: Update OS package caches for Debian
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - file-backup
    - file-backup-update-packages

- name: Update OS package caches for CentOS
  dnf:
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - file-backup
    - file-backup-update-packages

- name: Update OS packages
  package:
    name: '*'
    state: latest
  tags:
    - file-backup
    - file-backup-update-packages

# For Ubuntu
- name: Install OS packages for Debian
  package:
    name: "{{ file_backup_debian_install }}"
    state: latest
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - file-backup
    - file-backup-install-packages

# For CentOS
- name: Install OS packages for CentOS
  package:
    name: "{{ file_backup_redhat_install }}"
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - file-backup
    - file-backup-install-packages

# ------------------------------------------
# Install AWS cli if log backup to S3 is enabled.
# ------------------------------------------
- name: Install AWS cli if log backup to S3 is enabled
  ansible.builtin.include_tasks: install_aws_cli.yml
  when: file_backup_s3_transfer_enable
  tags:
    - file-backup
    - file-backup-install-aws-cli

# -----------------------------------------
# Create backup group and user
# -----------------------------------------
- name: Create an backup group and user
  ansible.builtin.include_tasks: create_backup_user.yml
  tags:
    - file-backup
    - file-backup-create-backup-user

# -----------------------------------------
# Log backup in local
# -----------------------------------------
# Install backup scripts
- name: Install backup scripts
  ansible.builtin.include_tasks: install_file_backup_scripts.yml
  tags:
    - file-backup
    - file-backup-install-backup-scripts

- name: Setup backup service and timer
  ansible.builtin.include_tasks: install_file_backup_service.yml
  tags:
    - file-backup
    - file-backup-install-backup-service

# -----------------------------------------
# Log backup transfer to s3
# -----------------------------------------
# Install s3 transfer scripts
- name: Install s3 transfer scripts
  ansible.builtin.include_tasks: install_s3_transfer_scripts.yml
  when: file_backup_s3_transfer_enable
  tags:
    - file-backup
    - file-backup-install-s3-transfer-scripts

- name: Install s3 download scripts
  ansible.builtin.include_tasks: install_s3_download_scripts.yml
  when: file_backup_s3_transfer_enable
  tags:
    - file-backup
    - file-backup-install-s3-download-scripts

# Setup ssh for s3 transfer user to backup servers
- name: Setup ssh for s3 transfer user to backup servers
  ansible.builtin.include_tasks: setup_ssh_dir.yml
  when: file_backup_s3_transfer_enable
  tags:
    - file-backup
    - file-backup-setup-ssh-for-s3-transfer

- name: Create and setup AWS credentials
  ansible.builtin.include_tasks: setup_aws_credentials.yml
  when: file_backup_s3_transfer_enable
  tags:
    - file-backup
    - file-backup-to-s3
    - file-backup-create-aws-credentials

- name: Setup AWS config
  ansible.builtin.include_tasks: setup_aws_config.yml
  when: file_backup_s3_transfer_enable
  tags:
    - file-backup
    - file-backup-to-s3
    - file-backup-create-aws-config

# -----------------------------------------
# Log transfer to backup servers
# -----------------------------------------
# Setup ssh for log transfer user to backup servers
- name: Setup ssh for log transfer user to backup servers
  ansible.builtin.include_tasks: setup_ssh_dir.yml
  when: file_backup_log_transfer_enable
  tags:
    - file-backup
    - file-backup-setup-ssh-for-log-transfer

# Install log transfer scripts
- name: Install log transfer scripts
  ansible.builtin.include_tasks: install_log_transfer_scripts.yml
  when: file_backup_log_transfer_enable
  tags:
    - file-backup
    - file-backup-install-log-transfer-scripts

# Setup log transfer service and timer
- name: Setup log transfer service and timer
  ansible.builtin.include_tasks: install_log_transfer_service.yml
  when: file_backup_log_transfer_enable
  tags:
    - file-backup
    - file-backup-install-log-transfer-service
